// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfXoczYNF_-Gh0BYcGHuNnqKPDjeh4euI',
    appId: '1:774297660894:web:03d8c0fc2aaf15323d814f',
    messagingSenderId: '774297660894',
    projectId: 'project-7e5c8',
    authDomain: 'project-7e5c8.firebaseapp.com',
    storageBucket: 'project-7e5c8.firebasestorage.app',
    measurementId: 'G-V0V32L5ZXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxd0MroGAsVLVAPym8glJWc1WV1qDY0l4',
    appId: '1:774297660894:android:297102faa3b695e23d814f',
    messagingSenderId: '774297660894',
    projectId: 'project-7e5c8',
    storageBucket: 'project-7e5c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZNoYYO4M0kD9O9VkfdDMTdl-mcQeAzg0',
    appId: '1:774297660894:ios:d8da7fd5eba390283d814f',
    messagingSenderId: '774297660894',
    projectId: 'project-7e5c8',
    storageBucket: 'project-7e5c8.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZNoYYO4M0kD9O9VkfdDMTdl-mcQeAzg0',
    appId: '1:774297660894:ios:d8da7fd5eba390283d814f',
    messagingSenderId: '774297660894',
    projectId: 'project-7e5c8',
    storageBucket: 'project-7e5c8.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfXoczYNF_-Gh0BYcGHuNnqKPDjeh4euI',
    appId: '1:774297660894:web:b3e10a9ee02c67de3d814f',
    messagingSenderId: '774297660894',
    projectId: 'project-7e5c8',
    authDomain: 'project-7e5c8.firebaseapp.com',
    storageBucket: 'project-7e5c8.firebasestorage.app',
    measurementId: 'G-ST3SBNM130',
  );

}