// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxiJJmZd2co39r4WA5tRljE4hwSm-w1yc',
    appId: '1:483575085485:web:86f47287d04ff21e1b4924',
    messagingSenderId: '483575085485',
    projectId: 'final-38e63',
    authDomain: 'final-38e63.firebaseapp.com',
    storageBucket: 'final-38e63.firebasestorage.app',
    measurementId: 'G-Q8Z7N1SNEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoJJMMUrRRIFnl6cZN_H8PQd03f_JMEs0',
    appId: '1:483575085485:android:6385e218d3e248af1b4924',
    messagingSenderId: '483575085485',
    projectId: 'final-38e63',
    storageBucket: 'final-38e63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnqtOeoHv_eoF4AkYcaOg6MB1Ek7GjJFY',
    appId: '1:483575085485:ios:01b8d7ab8105748c1b4924',
    messagingSenderId: '483575085485',
    projectId: 'final-38e63',
    storageBucket: 'final-38e63.firebasestorage.app',
    iosBundleId: 'com.example.weatherapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnqtOeoHv_eoF4AkYcaOg6MB1Ek7GjJFY',
    appId: '1:483575085485:ios:01b8d7ab8105748c1b4924',
    messagingSenderId: '483575085485',
    projectId: 'final-38e63',
    storageBucket: 'final-38e63.firebasestorage.app',
    iosBundleId: 'com.example.weatherapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxiJJmZd2co39r4WA5tRljE4hwSm-w1yc',
    appId: '1:483575085485:web:8c827a9e9d5a0e6f1b4924',
    messagingSenderId: '483575085485',
    projectId: 'final-38e63',
    authDomain: 'final-38e63.firebaseapp.com',
    storageBucket: 'final-38e63.firebasestorage.app',
    measurementId: 'G-NPQFPJBNCD',
  );
}
